apiVersion: v1
kind: Service
metadata:
  name: color-app-service
  namespace: color-app
spec:
  selector:
    app: color-app
  ports:
    - protocol: TCP
      port: 5000
      name: flask
  type: NodePort